name: iesportocristo_exposed
description: "The Darkside of IES Porto Cristo"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0-282.3.beta <4.0.0"

dependencies:
  cloud_firestore: ^4.17.3
  dart_openai: ^5.1.0
  envied: ^0.5.4+1
  firebase_analytics: ^10.10.6
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.1.2
  image_picker: ^1.1.1
  image_picker_for_web: ^3.0.4
  path: ^1.9.0
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
