name: iesportocristo_exposed
description: "The Darkside of IES Porto Cristo"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0-282.3.beta <4.0.0"

dependencies:
  animated_flip_counter: ^0.3.4
  cloud_firestore: ^4.17.3
  dart_openai: ^5.1.0
  envied: ^0.5.4+1
  firebase_analytics: ^10.10.6
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  firebase_ui_auth: ^1.14.0
  firebase_ui_oauth_google: ^1.3.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.1.2
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_cropper: ^6.0.0
  image_picker: ^1.1.1
  image_picker_for_web: ^3.0.4
  just_audio: ^0.9.38
  path: ^1.9.0
  provider: ^6.1.2
  remove_diacritic: ^0.9.0
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
