name: Build and Deploy Flutter Web App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.22.1"

      - name: Install dependencies
        run: flutter pub get

      - name: "Create env file"
        run: |
          touch .env
          echo OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }} >> .env

      - name: "Run build runner"
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build web
        run: flutter build web --web-renderer canvaskit --release

      - name: Upload web build to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: build/web

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_IESPORTOCRISTO_EXPOSED }}
          channelId: live
          projectId: iesportocristo-exposed
